### ISSUE TITLE
Release v2 of PKIjs

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/pkijs-es6#17]
This bug is intended to track the items necessarry to release version 2 of PKIjs:
- [x] Add PKCS12 Functionality (#15)
- [x] Add P7B sample (#14)
- [x] Add CRL example (#11)
- [x] Add SMIME verification sample (#9)
- [x] Add SMIME encryption sample (#19)
- [x] Add PDF verification sample (#10)
- [ ] Update CSR help to ES6 version (https://github.com/PeculiarVentures/csrhelp/issues/38)
- [ ] Update tl-create to ES6 version (https://github.com/PeculiarVentures/tl-create/issues/33)
- [ ] XAdESjs to ES6 version (https://github.com/PeculiarVentures/xadesjs/issues/43)
- [ ] Take current es6 web example and convert to mocha/chai tests (#1)

**Comment by rmhrisk** [comment]
Decided to release without doing:
- [ ] Update CSR help to ES6 version (https://github.com/PeculiarVentures/csrhelp/issues/38)
- [ ] Update tl-create to ES6 version (https://github.com/PeculiarVentures/tl-create/issues/33)
- [ ] XAdESjs to ES6 version (https://github.com/PeculiarVentures/xadesjs/issues/43)

Have bugs in each repo for tracking these activities.

We have completed the release of v2, closing.
